
package com.example.android.unscramble.ui.game


const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

val allWordsList: List<String> =
    listOf(

        "Luna",
        "gato",
        "jardín",
        "espejo",
        "viento",
        "mar",
        "montaña",
        "sombra",
        "risa",
        "nube",
        "silencio",
        "murmullo",
        "faro",
        "trenza",
        "melodía",
        "lluvia",
        "bosque",
        "estrella",
        "cometa",
        "fuego",
        "puente",
        "río",
        "noche",
        "susurro",
        "cascada",
        "campana",
        "enigma",
        "neblina",
        "trébol",
        "reloj",
        "diamante",
        "laberinto",
        "ola",
        "ala",
        "quimera",
        "esfera",
        "primavera",
        "arco iris",
        "crisálida",
        "girasol",
        "encanto",
        "caracol",
        "oráculo",
        "rapsodia",
        "acuarela",
        "góndola",
        "sinfonía",
        "zafiro",
        "manantial",
        "canto",
        "esencia",
        "travesía",
        "fragancia",
        "alquimia",
        "trampantojo",
        "crisol",
        "rincón",
        "murciélago",
        "jade",
        "laberinto",
        "arrebato",
        "éxtasis",
        "mirada",
        "ébano",
        "fulgor",
        "mirada",
        "índigo",
        "carnaval",
        "rincon", "lamento", "vendaval", "anhelo", "mirada", "serenata", "perla", "estirpe", "elixir", "bálsamo", "elixir", "crisol", "diamante", "corriente", "arrebato", "azabache", "diáfano", "canto", "travesía", "arcano", "éxtasis", "alboroto", "mirada", "murmullo", "fulgor", "murciélago", "esmeralda", "corriente", "quimera", "enigma", "ala", "sinfonía", "fragor", "góndola", "canto", "crisol", "estrella", "éxtasis", "alquimia", "fulgor", "serenata", "faro", "góndola", "montaña", "cascabel", "oráculo", "espejismo", "rincon", "cometa", "zumbido", "acuarela", "esencia", "brisa", "luna", "alquimia", "travesía", "arcano", "sinfonía", "murciélago", "estrella", "carnaval", "esmeralda", "estirpe", "esfera", "zafiro", "río", "esencia", "crisol", "fulgor", "acuarela", "canto", "serenata", "laberinto", "enigma", "rincon", "cometa", "trampantojo", "vendaval", "bálsamo", "caracol", "estirpe", "éxtasis", "ala", "mirada", "espejismo", "cascada", "diamante", "crisálida", "mirada", "neblina", "jade", "gato", "oráculo", "alquimia", "espejo", "serenata", "ébano", "canto", "arco iris", "crisálida", "elixir", "rapsodia", "faro", "esfera", "montaña", "cascabel", "trébol", "esmeralda", "diamante", "ala", "arco", "laberinto", "cometa", "río", "zafiro", "trébol", "nevada", "éxtasis", "lamento", "brisa", "estrella", "espejismo", "cascada", "vendaval", "arcano", "trébol", "canto", "fulgor", "encanto", "esencia", "estrella", "murciélago", "luna", "cometa", "diamante", "esmeralda", "acuarela", "ala", "trampantojo", "arrebato", "neblina", "murmullo", "oráculo", "esfera", "cascabel", "góndola", "jade", "alquimia", "estirpe", "lamento", "arco iris", "río", "trébol", "ébano", "caracol", "arcano", "espejo", "serenata", "crisálida", "canto", "brisa", "esencia", "cometa", "laberinto", "oráculo", "espejismo", "gato", "jade", "lamento", "mirada", "ala", "fulgor", "corriente", "cascabel", "esfera", "montaña", "trampantojo", "rincon", "nevada", "alquimia", "ébano", "zumbido", "caracol", "esmeralda", "estrella", "diamante", "esencia", "luna", "crisol", "vendaval", "encanto", "acuarela", "arcano", "rapsodia", "canto", "faro", "arco iris", "góndola", "mirada", "espejismo", "río", "trébol", "montaña", "estrella", "serenata", "encanto", "cascabel", "lamento", "cometa", "esencia", "brisa", "oráculo", "rincon", "serenata", "caracol", "trébol", "arrebato", "espejo", "montaña", "esfera", "encanto", "canto", "esencia", "cascabel", "estirpe", "río", "trampantojo", "espejismo", "rincon", "gato", "arco iris", "serenata", "oráculo", "cascada", "estrella", "nevada", "esencia", "lamento", "esmeralda", "trampantojo", "faro", "canto", "espejo", "brisa", "encanto", "arco iris", "oráculo", "gato", "esfera", "cascabel", "esencia", "río", "trampantojo", "estrella", "góndola", "luna", "encanto", "serenata", "arco iris", "espejo"
    )